### ISSUE TITLE
How to get the file “ video_info.csv”?. 

### ISSUE THREAD

**Issue by tianshu-zhu** [skelemoa/tal-hmo#5]
I am following the instructions https://github.com/skelemoa/tal-hmo to reproduce your paper. When I tried to extract the audio feature using python extractVGGishFeatures.py, I encountered the following error. Could you explain how to get the file “ video_info.csv”?. 

Traceback (most recent call last):
  File "/media/tianshu/DATA/tianshu/avfusion/extractVGGishFeatures.py", line 44, in <module>
    data = np.genfromtxt('video_info.csv', delimiter=',', dtype=str)
  File "/home/tianshu/anaconda3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1793, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/tianshu/anaconda3/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/tianshu/anaconda3/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: video_info.csv not found.

**Comment by Wojak27** [comment]
Probably irrelevant anymore, but wort posting for the next person that has this issue... I made it work without the file. What you need in the end is the number of frames the video features have been sampled with and the amount of seconds per video (this would be in the missing csv file). 

The way I made it work for myself is, I took the amount of frames per second in the video features and then took the number of seconds, often contained in the annotations file (at least for THUMOS14) for each video, which created a dict, "frames" which you can see in the code. In the end you want frames dict to look like this: {"video_001":40234,"video_002":432, etc...} 

Hope it helps whomever
